version: '3'
services:
  flaskapp:
    build: ./backend
    ports:
      - "6000:5000"  # Map container port 5000 to host port 6000
    volumes:
      - ./ssl:/backend/ssl  # Mount SSL certificates into the container
    environment:
      - FLASK_ENV=production
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "main:app"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # HTTP port
      - "443:443" # HTTPS port
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - flaskapp
