version: '3'

services:
  flaskapp:
    build: ./backend
    ports:
      - "5000:5000"  # Expose container port 5000 on host port 5000
    volumes:
      - ./ssl:/backend/ssl  # Mount SSL certificates if needed
    environment:
      - FLASK_ENV=production
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "main:app"]
