version: '3'

services:
  flaskapp:
    build: ./backend
    ports:
      - "8443:5000"  # Map container port 5000 to host port 8443
    volumes:
      - ./ssl:/backend/ssl  # Mount SSL certificates into the container
    environment:
      - FLASK_ENV=production
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "main:app"]
