version: '3'

services:
  flaskapp:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./ssl:/backend/ssl
      - ../compliance_mounted_volumes/images:/backend/uploads/images  # Mount host directory to container
      - ../compliance_mounted_volumes/database:/backend/instance  # Mount host directory to container
    environment:
      - FLASK_ENV=production
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "main:app"]

volumes:
  flaskapp-images:
  flaskapp-instance:
